package encryptiontest;

import org.junit.Test;

public class test {
@Test
public void test(){
	System.out.print(2000/7);
	
}
@Test
public void findKey(){
	String cipherText = "VCBAHYDMUHVPIRMDNWTSQGYHPZCYSPGBXUIFTGKQHAHDYKAODGTMPMNUQPKMIBQHWXZXUIFTGKQBMHTLUQIDBDMAFCXZXMADUFVTKPALDWSPPQHZCDGMXIHSHRWGCEBIBBNOFHWXGPIOMCMPUUPSPKQEUURTTZZYEHARQYMGFTRWGUDSBBAFUWSCEWAEFVTKMUMVCWGIZXYWHLPAQMFSVGZNTWPGWPXQRGTBTYDUAHWYCXMNXAVITBABSQMYSXMPUHWOCWWRWAIGLMQPUSUHZMFXVTKODORTLTGEQAIAWVFVQICDQZXFCPYTKVGHATEDYZQTGMHYDGEXIWMFCBXQRBQQPGPQFBWITVPGMFNVIZBMFSEGNLUBVAMDMQZUMWNYOWKBTFIYSHAMIUZHHXDUYFCHMIKIZWHUMSAUBVAMDNAPJMATYPCTLVFQMBIFMMHPOCWQPIZHZGWIQTOIMWPIEISWMZFKHWXXAIDQWBTPVGFHMWGNOFNBVSCPCCMSZIIKWTBBIEGTLAQXYSWXZNYMIIRXQLTOELIEMTSHTBFBQFTPQFBFVTLCZFUUWMOXCZHXGOPIIBDGPQLTSPWXQLTOELBTYESCLMAZDSABMRUFSCVWGHFSGBVSMAATHVQQTCHHWNPUCJLTKWAIAWPMPQBDVWZHQQIBWZQUHWMPQNDOVXLKJQFWTXEBABTLBBCFMUHZTYDMDNBTUZRAHVQFUBTLAMHKKPRQXYMBIYWDQMFSTVPNMYXGOTYDZXMBXYTOCWQEUURPPSIUDRARUMLDMBXKKHFVXTCZQUHIBVSFKWWTLTCFIEHVMMAJTKMUAZFTFMPSRCGAMDNQOGLATYEOINXMNABRXLDYIVTKPMHPOLTGMHPGPBLICFVHHUQUEDTKQFSPCCMJQMUZARQIUEOABBFFQOCGWKYPWBGWFVQWCZAUFXMXTUMMWWCZGAOFCSHUQNTSWHVAODCUUMOIYWCZUKQUTTMWYSUBIXVEYEIGIZUMQQNGBTCMPJKAFIGHATCSBUBVTVPWMZAXLYYMTJGVKXQOGBBEJQFUXKFFKGLXMFIRMDNATYEOXWJGNKCJDVAQKCJWWZNIOCMBASQGXWWUPQUDMVQPQFBBVPQTOIRWGPQUDMGAOPCCMZQUXZNPIZNFCPGLUXABIXQFBQFLXTXIRQDNZEYFVPMAQNFZTLQFCEOXWAFCRTARJGNURDGBEYQOCRBTCZUIHTMOSVPMBTYDSHGWFBUBVYCZHKOQHCFUBFDIWEUXBDBVPYQRHTQPWKBIAQMMAATUWPSYWVABMWOSEMGAOZSMMBUGQUDHLNSQMDNDQWTSTKMPGQIEOMDSYIRAIZXIWIAIRCZOANVOIZHGHTXUNZTUCDMFCUFMDLUATGBEBQJPGQEBQRIAZAOSVIAMFLQSHMPUHWWCZWHYDHWXQZNQFKBMICFGIKCOEYSPLJQCZUEKWRIGBSEGGHEOIBARUOHDKGUNAQRNZDYPHDFMEOPRTGTKNTOIBEAOXRVHLAQZHDMPQPUZATOQUZRAHWWOBPPNMDMFSXGAAGQPDWGAOSVIMWNYWSTIQZAMBTRMAHFVTYMXFAKPMBTYEOBXBUGQWIPWGFPPTPQEYFCPETMSMBNLCEJUQXHVEBQAXZPFBMJTTAFITWHUMUHSGJLXQWFSSBZQGQAQXZQXTCLIWULAHWTLDYXWTWWZGKRXITAGMQNTKOIDRXGOXSUKTGBFIFVTEQFNXSWHCEYIWIABTYMDPKBYYZHHVIDXUBHXZFYPWCMPQQUBSHEIBQFTBSZYIVTEWPAQRPGLFUBDTWWZNTSSHWDUZCAWEAGMBRTUQUZRDIMZYPWIZWAXMTIXZZIABXLIUXBZTTAMHFZNBAPLNOJXZENQWCBVEBQGITZQXMHBXPMPQBIRWGBQOGWPQUDRLAIFUNCJMPUGIVPMINIGHWBUTYEHDHSFIAYSXIPHAHDHSNSFVTIMDFUQTUGFBQDDEQOYUUPLXQXPCNHCYYMBIAMK";
	int arrNum = 2000/7;
    char[] cipherArray = cipherText.toCharArray();
	char[] array0 = new char[arrNum];
	char[] array1 = new char[arrNum];
	char[] array2 = new char[arrNum];
	char[] array3 = new char[arrNum];
	char[] array4 = new char[arrNum];
	char[] array5 = new char[arrNum];
	char[] array6 = new char[arrNum];
	
	for(int i = 0; i < arrNum * 7; i++){
		switch (i % 7){
		case 0: 
			array0[i/7] =  cipherArray[i];
		case 1: 
			array1[i/7] =  cipherArray[i];
		case 2: 
			array2[i/7] =  cipherArray[i];
		case 3: 
			array3[i/7] =  cipherArray[i];
		case 4: 
			array4[i/7] =  cipherArray[i];
		case 5: 
			array5[i/7] =  cipherArray[i];
		case 6: 
			array6[i/7] =  cipherArray[i];
	}
	}
//	return (char)(26 - shiftCipherDecryption(array0) + 65) + "\t"
//	+ (char)(26 - shiftCipherDecryption(array1) + 65) + "\t" + (char)(26 - shiftCipherDecryption(array2) + 65) + "\t"
//	+ (char)(26 - shiftCipherDecryption(array3) + 65) + "\t" + (char)(26 - shiftCipherDecryption(array4) + 65) + "\t"
//	+ (char)(26 - shiftCipherDecryption(array5) + 65) + "\t" + (char)(26 - shiftCipherDecryption(array6) + 65) + "\t";
    for(int i = 0; i < array0.length; i++){
    	System.out.print(array0[i]);
    }
} 
}
